collision_monitor:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    odom_topic: /odom
    cmd_vel_in_topic: /cmd_vel
    cmd_vel_out_topic: /cmd_vel_safe
    state_topic: /collision_monitor_state
    transform_tolerance: 0.2
    source_timeout: 0.8
    base_shift_correction: true
    stop_pub_timeout: 2.0

    polygons: [front_slowdown, front_stop]
    front_slowdown:
      type: polygon
      points: [1.00, 0.28, 1.00, -0.28, 0.35, -0.28, 0.35, 0.28]
      action_type: slowdown
      slowdown_ratio: 0.35
      max_points: 8
      visualize: true
      polygon_pub_topic: /collision_monitor/front_slowdown
      enabled: true
    front_stop:
      type: polygon
      points: [0.70, 0.22, 0.70, -0.22, 0.35, -0.22, 0.35, 0.22]
      action_type: stop
      max_points: 4
      visualize: true
      polygon_pub_topic: /collision_monitor/front_stop
      enabled: true

    observation_sources: [scan]
    scan:
      type: scan
      topic: /scan_filtered
      source_timeout: 0.8
      enabled: true
